# Stage 1: Build the Angular app
FROM node:18.16.0 as build

WORKDIR /app

COPY angular-accounting/package*.json ./

RUN npm ci --quiet

COPY angular-accounting .

RUN npm run build

# Stage 2: Serve the Angular app using Nginx
FROM nginx:latest

COPY --from=build /app/dist/angular-accounting /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
